[package]
name = "sos-artifact"
version = "0.8.6"
edition = "2021"
description = "Types for release artifact meta data"
homepage = "https://saveoursecrets.com"
license = "MIT OR Apache-2.0"
repository = "https://github.com/saveoursecrets/sdk"

[dependencies]
url.workspace = true
thiserror.workspace = true
serde.workspace = true
hex.workspace = true
time.workspace = true
semver = { version = "1", features = ["serde"] }

[dev-dependencies]
anyhow = "1"
serde_json = "1"
